apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: nginx
    tier: backend
    role: webserver
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 2
  # selector can be applied automatically 
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   role: master
  #   tier: backend
  template:
    metadata:
      labels:
        app: nginx
        role: webserver
        tier: backend
    spec:
      containers:
      - name: master
        image: nginx  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
